const pokedex = [
    {
        image:'Images/bulbasaur.png',
        id: 1,
        name: "Bulbasaur",
        type1: "Grass",
        type2: "Poison",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Bulbasaur_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Ivysaur.png',
        id: 2,
        name: "Ivysaur",
        type1: "Grass",
        type2: "Poison",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Ivysaur_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Venusaur.png',
        id: 3,
        name: "Venusaur",
        type1: "Grass",
        type2: "Poison",
        generation: 1,
        stage: "Third",
        link: "https://bulbapedia.bulbagarden.net/wiki/Venusaur_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Charmander.png',
        id: 4,
        name: "Charmander",
        type1: "Fire",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Charmander_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Charmeleon.png',
        id: 5,
        name: "Charmeleon",
        type1: "Fire",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Charmeleon_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Charizard.png',
        id: 6,
        name: "Chrizard",
        type1: "Fire",
        type2: "Flying",
        generation: 1,
        stage: "Third",
        link: "https://bulbapedia.bulbagarden.net/wiki/Charizard_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Squirtle.png',
        id: 7,
        name: "Squirtle",
        type1: "Water",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Squirtle_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Wartortle.png',
        id: 8,
        name: "Wartortle",
        type1: "Water",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Wartortle_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Blastoise.png',
        id: 9,
        name: "Blastoise",
        type1: "Water",
        type2: "None",
        generation: 1,
        stage: "Third",
        link: "https://bulbapedia.bulbagarden.net/wiki/Blastoise_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Caterpie.png',
        id: 10,
        name: "Caterpie",
        type1: "Bug",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Caterpie_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Metapod.png',
        id: 11,
        name: "Metapod",
        type1: "Bug",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Metapod_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Butterfree.png',
        id: 12,
        name: "Butterfree",
        type1: "Bug",
        type2: "Flying",
        generation: 1,
        stage: "Third",
        link: "https://bulbapedia.bulbagarden.net/wiki/Butterfree_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Weedle.png',
        id: 13,
        name: "Weedle",
        type1: "Bug",
        type2: "Poison",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Weedle_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Kakuna.png',
        id: 14,
        name: "Kakuna",
        type1: "Bug",
        type2: "Poison",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Kakuna_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Beedrill.png',
        id: 15,
        name: "Beedrill",
        type1: "Bug",
        type2: "Poison",
        generation: 1,
        stage: "Third",
        link: "https://bulbapedia.bulbagarden.net/wiki/Beedrill_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Pidgey.png',
        id: 16,
        name: "Pidgey",
        type1: "Normal",
        type2: "Flying",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Pidgey_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Pidgeotto.png',
        id: 17,
        name: "Pidgeotto",
        type1: "Normal",
        type2: "Flying",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Pidgeotto_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Pidgeot.png',
        id: 18,
        name: "Pidgeot",
        type1: "Normal",
        type2: "Flying",
        generation: 1,
        stage: "Third",
        link: "https://bulbapedia.bulbagarden.net/wiki/Pidgeot_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Rattata.png',
        id: 19,
        name: "Rattata",
        type1: "Normal",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Rattata_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Raticate.png',
        id: 20,
        name: "Raticate",
        type1: "Normal",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Raticate_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Spearow.png',
        id: 21,
        name: "Spearow",
        type1: "Normal",
        type2: "Flying",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Spearow_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Fearow.png',
        id: 22,
        name: "Fearow",
        type1: "Normal",
        type2: "Flying",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Fearow_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Ekans.png',
        id: 23,
        name: "Ekans",
        type1: "Poison",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Ekans_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Arbok.png',
        id: 24,
        name: "Arbok",
        type1: "Poison",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Arbok_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Pikachu.png',
        id: 25,
        name: "Pikachu",
        type1: "Electric",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Pikachu_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Raichu.png',
        id: 26,
        name: "Raichu",
        type1: "Electric",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Raichu_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Sandshrew.png',
        id: 27,
        name: "Sandshrew",
        type1: "Ground",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Sandshrew_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Sandslash.png',
        id: 28,
        name: "Sandslash",
        type1: "Ground",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Sandshrew_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Nidoran(Female).png',
        id: 29,
        name: "Nidoran(Female)",
        type1: "Poison",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Nidoran%E2%99%80_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Nidorina.png',
        id: 30,
        name: "Nidorina",
        type1: "Poison",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Nidorina_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Nidoqueen.png',
        id: 31,
        name: "Nidoqueen",
        type1: "Poison",
        type2: "Ground",
        generation: 1,
        stage: "Third",
        link: "https://bulbapedia.bulbagarden.net/wiki/Nidoqueen_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Nidoran(male).png',
        id: 32,
        name: "Nidoran(male)",
        type1: "Poison",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Nidoran%E2%99%82_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Nidorino.png',
        id: 33,
        name: "Nidorino",
        type1: "Poison",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Nidorino_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Nidoking.png',
        id: 34,
        name: "Nidoking",
        type1: "Poison",
        type2: "Ground",
        generation: 1,
        stage: "Third",
        link: "https://bulbapedia.bulbagarden.net/wiki/Nidoking_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Clefairy.png',
        id: 35,
        name: "Clefairy",
        type1: "Fairy",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Clefairy_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Clefable.png',
        id: 36,
        name: "Clefable",
        type1: "Fairy",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Clefable_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Vulpix.png',
        id: 37,
        name: "Vulpix",
        type1: "Fire",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Vulpix_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Ninetales.png',
        id: 38,
        name: "Ninetales",
        type1: "Fire",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Ninetales_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Jigglypuff.png',
        id: 39,
        name: "Jigglypuff",
        type1: "Normal",
        type2: "Fairy",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Jigglypuff_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Wigglytuff.png',
        id: 40,
        name: "Wigglytuff",
        type1: "Normal",
        type2: "Fairy",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Wigglytuff_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Zubat.png',
        id: 41,
        name: "Zubat",
        type1: "Poison",
        type2: "Flying",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Zubat_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Golbat.png',
        id: 42,
        name: "Golbat",
        type1: "Poison",
        type2: "Flying",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Golbat_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Oddish.png',
        id: 43,
        name: "Oddish",
        type1: "Grass",
        type2: "Poison",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Oddish_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Gloom.png',
        id: 44,
        name: "Gloom",
        type1: "Grass",
        type2: "Poison",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Gloom_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Vileplume.png',
        id: 45,
        name: "Vileplume",
        type1: "Grass",
        type2: "Poison",
        generation: 1,
        stage: "Third",
        link: "https://bulbapedia.bulbagarden.net/wiki/Vileplume_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Paras.png',
        id: 46,
        name: "Paras",
        type1: "Bug",
        type2: "Grass",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Paras_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Parasect.png',
        id: 47,
        name: "Parasect",
        type1: "Bug",
        type2: "Grass",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Parasect_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Venonat.png',
        id: 48,
        name: "Venonat",
        type1: "Bug",
        type2: "Poison",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Venonat_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Venomoth.png',
        id: 49,
        name: "Venomoth",
        type1: "Bug",
        type2: "Poison",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Venomoth_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Diglett.png',
        id: 50,
        name: "Diglett",
        type1: "Ground",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Diglett_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Dugtrio.png',
        id: 51,
        name: "Dugtrio",
        type1: "Ground",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Dugtrio_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Meowth.png',
        id: 52,
        name: "Meowth",
        type1: "Normal",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Meowth_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Persian.png',
        id: 53,
        name: "Persian",
        type1: "Normal",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Persian_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Psyduck.png',
        id: 54,
        name: "Psyduck",
        type1: "Water",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Psyduck_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Golduck.png',
        id: 55,
        name: "Golduck",
        type1: "Water",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Golduck_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Mankey.png',
        id: 56,
        name: "Mankey",
        type1: "Fighting",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Mankey_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Primeape.png',
        id: 57,
        name: "Primeape",
        type1: "Fighting",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Primeape_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Growlithe.png',
        id: 58,
        name: "Growlithe",
        type1: "Fire",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Growlithe_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Arcanine.png',
        id: 59,
        name: "Arcanine",
        type1: "Fire",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Arcanine_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Poliwag.png',
        id: 60,
        name: "Poliwag",
        type1: "Water",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Poliwag_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Poliwhirl.png',
        id: 61,
        name: "Poliwhirl",
        type1: "Water",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Poliwhirl_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Poliwrath.png',
        id: 62,
        name: "Poliwrath",
        type1: "Water",
        type2: "Fighting",
        generation: 1,
        stage: "Third",
        link: "https://bulbapedia.bulbagarden.net/wiki/Poliwrath_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Abra.png',
        id: 63,
        name: "Abra",
        type1: "Psychic",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Abra_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Kadabra.png',
        id: 64,
        name: "Kadabra",
        type1: "Psychic",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Kadabra_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Alakazam.png',
        id: 65,
        name: "Alakazam",
        type1: "Psychic",
        type2: "None",
        generation: 1,
        stage: "Third",
        link: "https://bulbapedia.bulbagarden.net/wiki/Alakazam_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Machop.png',
        id: 66,
        name: "Machop",
        type1: "Fighting",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Machop_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Machoke.png',
        id: 67,
        name: "Machoke",
        type1: "Fighting",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Machoke_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Machamp.png',
        id: 68,
        name: "Machamp",
        type1: "Fighting",
        type2: "None",
        generation: 1,
        stage: "Third",
        link: "https://bulbapedia.bulbagarden.net/wiki/Machamp_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Bellsprout.png',
        id: 69,
        name: "Bellsprout",
        type1: "Grass",
        type2: "Poison",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Bellsprout_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Weepinbell.png',
        id: 70,
        name: "Weepinbell",
        type1: "Grass",
        type2: "Poison",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Weepinbell_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Victreebel.png',
        id: 71,
        name: "Victreebel",
        type1: "Grass",
        type2: "Poison",
        generation: 1,
        stage: "Third",
        link: "https://bulbapedia.bulbagarden.net/wiki/Victreebel_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Tentacool.png',
        id: 72,
        name: "Tentacool",
        type1: "Water",
        type2: "Poison",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Tentacool_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Tentacruel.png',
        id: 73,
        name: "Tentacruel",
        type1: "Water",
        type2: "Poison",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Tentacruel_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Geodude.png',
        id: 74,
        name: "Geodude",
        type1: "Rock",
        type2: "Ground",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Geodude_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Graveler.png',
        id: 75,
        name: "Graveler",
        type1: "Rock",
        type2: "Ground",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Graveler_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Golem.png',
        id: 76,
        name: "Golem",
        type1: "Rock",
        type2: "Ground",
        generation: 1,
        stage: "Third",
        link: "https://bulbapedia.bulbagarden.net/wiki/Golem_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Ponyta.png',
        id: 77,
        name: "Ponyta",
        type1: "Fire",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Ponyta_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Rapidash.png',
        id: 78,
        name: "Rapidash",
        type1: "Fire",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Rapidash_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Slowpoke.png',
        id: 79,
        name: "Slowpoke",
        type1: "Water",
        type2: "Psychic",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Slowpoke_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Slowbro.png',
        id: 80,
        name: "Slowbro",
        type1: "Water",
        type2: "Psychic",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Slowbro_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Magnemite.png',
        id: 81,
        name: "Magnemite",
        type1: "Electric",
        type2: "Steel",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Magnemite_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Magneton.png',
        id: 82,
        name: "Magneton",
        type1: "Electric",
        type2: "Steel",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Magneton_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Farfetchd.png',
        id: 83,
        name: "Farfetch'd",
        type1: "Normal",
        type2: "Flying",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Farfetch%27d_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Doduo.png',
        id: 84,
        name: "Doduo",
        type1: "Normal",
        type2: "Flying",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Doduo_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Dodrio.png',
        id: 85,
        name: "Dodrio",
        type1: "Normal",
        type2: "Flying",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Dodrio_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Seel.png',
        id: 86,
        name: "Seel",
        type1: "Water",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Seel_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Dewgong.png',
        id: 87,
        name: "Dewgong",
        type1: "Water",
        type2: "Ice",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Dewgong_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Grimer.png',
        id: 88,
        name: "Grimer",
        type1: "Poison",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Grimer_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Muk.png',
        id: 89,
        name: "Muk",
        type1: "Poison",
        type2: "None",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Muk_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Shellder.png',
        id: 90,
        name: "Shellder",
        type1: "Water",
        type2: "None",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Shellder_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Cloyster.png',
        id: 91,
        name: "Cloyster",
        type1: "Water",
        type2: "Ice",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Cloyster_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Gastly.png',
        id: 92,
        name: "Gastly",
        type1: "Ghost",
        type2: "Poison",
        generation: 1,
        stage: "First",
        link: "https://bulbapedia.bulbagarden.net/wiki/Gastly_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Haunter.png',
        id: 93,
        name: "Haunter",
        type1: "Ghost",
        type2: "Poison",
        generation: 1,
        stage: "Second",
        link: "https://bulbapedia.bulbagarden.net/wiki/Haunter_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image:'Images/Gengar.png',
        id: 94,
        name: "Gengar",
        type1: "Ghost",
        type2: "Poison",
        generation: 1,
        stage: "Third",
        link: "https://bulbapedia.bulbagarden.net/wiki/Gengar_(Pok%C3%A9mon)",
        favorite: false
    },
    {
        image: 'Images/Onix.png',
        id: 95,
        name: 'Onix',
        type1: 'Rock',
        type2: 'Ground',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Onix_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Drowzee.png',
        id: 96,
        name: 'Drowzee',
        type1: 'Psychic',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Drowzee_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Hypno.png',
        id: 97,
        name: 'Hypno',
        type1: 'Psychic',
        type2: 'None',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Hypno_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Krabby.png',
        id: 98,
        name: 'Krabby',
        type1: 'Water',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Krabby_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Kingler.png',
        id: 99,
        name: 'Kingler',
        type1: 'Water',
        type2: 'None',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Kingler_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Voltorb.png',
        id: 100,
        name: 'Voltorb',
        type1: 'Electric',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Voltorb_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Electrode.png',
        id: 101,
        name: 'Electrode',
        type1: 'Electric',
        type2: 'None',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Electrode_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Exeggcute.png',
        id: 102,
        name: 'Exeggcute',
        type1: 'Grass',
        type2: 'Psychic',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Exeggcute_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Exeggutor.png',
        id: 103,
        name: 'Exeggutor',
        type1: 'Grass',
        type2: 'Psychic',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Exeggutor_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Cubone.png',
        id: 104,
        name: 'Cubone',
        type1: 'Ground',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Cubone_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Marowak.png',
        id: 105,
        name: 'Marowak',
        type1: 'Ground',
        type2: 'None',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Marowak_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Hitmonlee.png',
        id: 106,
        name: 'Hitmonlee',
        type1: 'Fighting',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Hitmonlee_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Hitmonchan.png',
        id: 107,
        name: 'Hitmonchan',
        type1: 'Fighting',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Hitmonchan_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Lickitung.png',
        id: 108,
        name: 'Lickitung',
        type1: 'Normal',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Lickitung_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Koffing.png',
        id: 109,
        name: 'Koffing',
        type1: 'Poison',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Koffing_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Weezing.png',
        id: 110,
        name: 'Weezing',
        type1: 'Poison',
        type2: 'None',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Weezing_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Rhyhorn.png',
        id: 111,
        name: 'Rhyhorn',
        type1: 'Rock',
        type2: 'Ground',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Rhyhorn_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Rhydon.png',
        id: 112,
        name: 'Rhydon',
        type1: 'Rock',
        type2: 'Ground',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Rhydon_(Pok%C3%A9mon)'
      },
      {
        image: 'Images/Chansey.png',
        id: 113,
        name: 'Chansey',
        type1: 'Normal',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Chansey_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Tangela.png',
        id: 114,
        name: 'Tangela',
        type1: 'Grass',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Tangela_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Kangaskhan.png',
        id: 115,
        name: 'Kangaskhan',
        type1: 'Normal',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Kangaskhan_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Horsea.png',
        id: 116,
        name: 'Horsea',
        type1: 'Water',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Horsea_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Seadra.png',
        id: 117,
        name: 'Seadra',
        type1: 'Water',
        type2: 'None',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Seadra_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Goldeen.png',
        id: 118,
        name: 'Goldeen',
        type1: 'Water',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Goldeen_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Seaking.png',
        id: 119,
        name: 'Seaking',
        type1: 'Water',
        type2: 'None',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Seaking_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Staryu.png',
        id: 120,
        name: 'Staryu',
        type1: 'Water',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Staryu_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Starmie.png',
        id: 121,
        name: 'Starmie',
        type1: 'Water',
        type2: 'Psychic',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Starmie_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/MrMime.png',
        id: 122,
        name: 'Mr. Mime',
        type1: 'Psychic',
        type2: 'Fairy',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Mr._Mime_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Scyther.png',
        id: 123,
        name: 'Scyther',
        type1: 'Bug',
        type2: 'Flying',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Scyther_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Jynx.png',
        id: 124,
        name: 'Jynx',
        type1: 'Ice',
        type2: 'Psychic',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Jynx_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Electabuzz.png',
        id: 125,
        name: 'Electabuzz',
        type1: 'Electric',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Electabuzz_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Magmar.png',
        id: 126,
        name: 'Magmar',
        type1: 'Fire',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Magmar_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Pinsir.png',
        id: 127,
        name: 'Pinsir',
        type1: 'Bug',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Pinsir_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Tauros.png',
        id: 128,
        name: 'Tauros',
        type1: 'Normal',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Tauros_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Magikarp.png',
        id: 129,
        name: 'Magikarp',
        type1: 'Water',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Magikarp_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Gyarados.png',
        id: 130,
        name: 'Gyarados',
        type1: 'Water',
        type2: 'Flying',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Gyarados_(Pok%C3%A9mon)'
      },
      {
        image: 'Images/Gyarados.png',
        id: 130,
        name: 'Gyarados',
        type1: 'Water',
        type2: 'Flying',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Gyarados_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Lapras.png',
        id: 131,
        name: 'Lapras',
        type1: 'Water',
        type2: 'Ice',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Lapras_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Ditto.png',
        id: 132,
        name: 'Ditto',
        type1: 'Normal',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Ditto_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Eevee.png',
        id: 133,
        name: 'Eevee',
        type1: 'Normal',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Eevee_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Vaporeon.png',
        id: 134,
        name: 'Vaporeon',
        type1: 'Water',
        type2: 'None',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Vaporeon_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Jolteon.png',
        id: 135,
        name: 'Jolteon',
        type1: 'Electric',
        type2: 'None',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Jolteon_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Flareon.png',
        id: 136,
        name: 'Flareon',
        type1: 'Fire',
        type2: 'None',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Flareon_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Porygon.png',
        id: 137,
        name: 'Porygon',
        type1: 'Normal',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Porygon_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Omanyte.png',
        id: 138,
        name: 'Omanyte',
        type1: 'Rock',
        type2: 'Water',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Omanyte_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Omastar.png',
        id: 139,
        name: 'Omastar',
        type1: 'Rock',
        type2: 'Water',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Omastar_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Kabuto.png',
        id: 140,
        name: 'Kabuto',
        type1: 'Rock',
        type2: 'Water',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Kabuto_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Kabutops.png',
        id: 141,
        name: 'Kabutops',
        type1: 'Rock',
        type2: 'Water',
        generation: 1,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Kabutops_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Aerodactyl.png',
        id: 142,
        name: 'Aerodactyl',
        type1: 'Rock',
        type2: 'Flying',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Aerodactyl_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Snorlax.png',
        id: 143,
        name: 'Snorlax',
        type1: 'Normal',
        type2: 'None',
        generation: 1,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Snorlax_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Articuno.png',
        id: 144,
        name: 'Articuno',
        type1: 'Ice',
        type2: 'Flying',
        generation: 1,
        stage: 'Legendary',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Articuno_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Zapdos.png',
        id: 145,
        name: 'Zapdos',
        type1: 'Electric',
        type2: 'Flying',
        generation: 1,
        stage: 'Legendary',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Zapdos_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Moltres.png',
        id: 146,
        name: 'Moltres',
        type1: 'Fire',
        type2: 'Flying',
        generation: 1,
        stage: 'Legendary',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Moltres_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Dratini.png',
        id: 147,
        name: 'Dratini',
        type1: 'Dragon',
        type2: 'None',
        generation: 1,
        stage: 'Legendary',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Mewtwo_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Dragonair.png',
        id: 148,
        name: 'Mewtwo',
        type1: 'Dragon',
        type2: 'None',
        generation: 1,
        stage: 'Legendary',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Mewtwo_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Dragonite.png',
        id: 149,
        name: 'Mew',
        type1: 'Dragon',
        type2: 'Flying',
        generation: 1,
        stage: 'Legendary',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Mew_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Mewtwo.png',
        id: 150,
        name: 'Mewtwo',
        type1: 'Psychic',
        type2: 'None',
        generation: 1,
        stage: 'Legendary',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Mewtwo_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Mew.png',
        id: 151,
        name: 'Mew',
        type1: 'Psychic',
        type2: 'None',
        generation: 1,
        stage: 'Legendary',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Mew_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Chikorita.png',
        id: 152,
        name: 'Chikorita',
        type1: 'Grass',
        type2: '',
        generation: 2,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Chikorita_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Bayleef.png',
        id: 153,
        name: 'Bayleef',
        type1: 'Grass',
        type2: '',
        generation: 2,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Bayleef_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Meganium.png',
        id: 154,
        name: 'Meganium',
        type1: 'Grass',
        type2: '',
        generation: 2,
        stage: 'Third',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Meganium_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Cyndaquil.png',
        id: 155,
        name: 'Cyndaquil',
        type1: 'Fire',
        type2: '',
        generation: 2,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Cyndaquil_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Quilava.png',
        id: 156,
        name: 'Quilava',
        type1: 'Fire',
        type2: '',
        generation: 2,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Quilava_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Typhlosion.png',
        id: 157,
        name: 'Typhlosion',
        type1: 'Fire',
        type2: '',
        generation: 2,
        stage: 'Third',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Typhlosion_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Totodile.png',
        id: 158,
        name: 'Totodile',
        type1: 'Water',
        type2: '',
        generation: 2,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Totodile_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Croconaw.png',
        id: 159,
        name: 'Croconaw',
        type1: 'Water',
        type2: '',
        generation: 2,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Croconaw_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Feraligatr.png',
        id: 160,
        name: 'Feraligatr',
        type1: 'Water',
        type2: '',
        generation: 2,
        stage: 'Third',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Feraligatr_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Sentret.png',
        id: 161,
        name: 'Sentret',
        type1: 'Normal',
        type2: '',
        generation: 2,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Sentret_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Furret.png',
        id: 162,
        name: 'Furret',
        type1: 'Normal',
        type2: '',
        generation: 2,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Furret_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Hoothoot.png',
        id: 163,
        name: 'Hoothoot',
        type1: 'Normal',
        type2: 'Flying',
        generation: 2,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Hoothoot_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Noctowl.png',
        id: 164,
        name: 'Noctowl',
        type1: 'Normal',
        type2: 'Flying',
        generation: 2,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Noctowl_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Ledyba.png',
        id: 165,
        name: 'Ledyba',
        type1: 'Bug',
        type2: 'Flying',
        generation: 2,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Ledyba_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Ledian.png',
        id: 166,
        name: 'Ledian',
        type1: 'Bug',
        type2: 'Flying',
        generation: 2,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Ledian_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Spinarak.png',
        id: 167,
        name: 'Spinarak',
        type1: 'Bug',
        type2: 'Poison',
        generation: 2,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Spinarak_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Ariados.png',
        id: 168,
        name: 'Ariados',
        type1: 'Bug',
        type2: 'Poison',
        generation: 2,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Ariados_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Crobat.png',
        id: 169,
        name: 'Crobat',
        type1: 'Poison',
        type2: 'Flying',
        generation: 2,
        stage: 'Third',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Crobat_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Chinchou.png',
        id: 170,
        name: 'Chinchou',
        type1: 'Water',
        type2: 'Electric',
        generation: 2,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Chinchou_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Lanturn.png',
        id: 171,
        name: 'Lanturn',
        type1: 'Water',
        type2: 'Electric',
        generation: 2,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Lanturn_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Pichu.png',
        id: 172,
        name: 'Pichu',
        type1: 'Electric',
        type2: null,
        generation: 2,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Pichu_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Cleffa.png',
        id: 173,
        name: 'Cleffa',
        type1: 'Fairy',
        type2: null,
        generation: 2,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Cleffa_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Igglybuff.png',
        id: 174,
        name: 'Igglybuff',
        type1: 'Normal',
        type2: 'Fairy',
        generation: 2,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Igglybuff_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Togepi.png',
        id: 175,
        name: 'Togepi',
        type1: 'Fairy',
        type2: null,
        generation: 2,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Togepi_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Togetic.png',
        id: 176,
        name: 'Togetic',
        type1: 'Fairy',
        type2: 'Flying',
        generation: 2,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Togetic_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Natu.png',
        id: 177,
        name: 'Natu',
        type1: 'Psychic',
        type2: 'Flying',
        generation: 2,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Natu_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Xatu.png',
        id: 178,
        name: 'Xatu',
        type1: 'Psychic',
        type2: 'Flying',
        generation: 2,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Xatu_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Mareep.png',
        id: 179,
        name: 'Mareep',
        type1: 'Electric',
        type2: null,
        generation: 2,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Mareep_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Flaaffy.png',
        id: 180,
        name: 'Flaaffy',
        type1: 'Electric',
        type2: null,
        generation: 2,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Flaaffy_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Ampharos.png',
        id: 181,
        name: 'Ampharos',
        type1: 'Electric',
        type2: null,
        generation: 2,
        stage: 'Third',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Ampharos_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Bellossom.png',
        id: 182,
        name: 'Bellossom',
        type1: 'Grass',
        type2: null,
        generation: 2,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Bellossom_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Marill.png',
        id: 183,
        name: 'Marill',
        type1: 'Water',
        type2: 'Fairy',
        generation: 2,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Marill_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Azumarill.png',
        id: 184,
        name: 'Azumarill',
        type1: 'Water',
        type2: 'Fairy',
        generation: 2,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Azumarill_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Sudowoodo.png',
        id: 185,
        name: 'Sudowoodo',
        type1: 'Rock',
        type2: null,
        generation: 2,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Sudowoodo_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Politoed.png',
        id: 186,
        name: 'Politoed',
        type1: 'Water',
        type2: null,
        generation: 2,
        stage: 'Third',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Politoed_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Hoppip.png',
        id: 187,
        name: 'Hoppip',
        type1: 'Grass',
        type2: 'Flying',
        generation: 2,
        stage: 'First',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Hoppip_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Skiploom.png',
        id: 188,
        name: 'Skiploom',
        type1: 'Grass',
        type2: 'Flying',
        generation: 2,
        stage: 'Second',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Skiploom_(Pok%C3%A9mon)',
        favorite: false
      },
      {
        image: 'Images/Jumpluff.png',
        id: 189,
        name: 'Jumpluff',
        type1: 'Grass',
        type2: 'Flying',
        generation: 2,
        stage: 'Third',
        link: 'https://bulbapedia.bulbagarden.net/wiki/Jumpluff_(Pok%C3%A9mon)',
        favorite: false
      },
]